// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDumKZWUie89oH231G46Gk828CNslVuK6Y',
    appId: '1:45686498205:web:c1789892214be5ff3c0574',
    messagingSenderId: '45686498205',
    projectId: 'whatsap-e8be6',
    authDomain: 'whatsap-e8be6.firebaseapp.com',
    storageBucket: 'whatsap-e8be6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Lk3q7wnW_TcBp3HpT9PgXj6toDru-lI',
    appId: '1:45686498205:android:ecb162c035f78f503c0574',
    messagingSenderId: '45686498205',
    projectId: 'whatsap-e8be6',
    storageBucket: 'whatsap-e8be6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuzN7udPm0v-gqI3uXyYdtlbyhn71PSHo',
    appId: '1:45686498205:ios:e88964ddfd056c963c0574',
    messagingSenderId: '45686498205',
    projectId: 'whatsap-e8be6',
    storageBucket: 'whatsap-e8be6.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
